# Generated by Django 2.1.1 on 2018-09-29 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='QuadTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=4)),
                ('location_ids', models.CharField(default='[]', max_length=1000)),
                ('divided', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'quadtree',
            },
        ),
        migrations.CreateModel(
            name='Rectangle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('w', models.FloatField()),
                ('h', models.FloatField()),
            ],
            options={
                'db_table': 'rectangle',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='quadtree',
            name='boundary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quadtree.Rectangle'),
        ),
        migrations.AddField(
            model_name='quadtree',
            name='child_ne',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_north_east', to='quadtree.QuadTree'),
        ),
        migrations.AddField(
            model_name='quadtree',
            name='child_nw',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_north_west', to='quadtree.QuadTree'),
        ),
        migrations.AddField(
            model_name='quadtree',
            name='child_se',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_south_east', to='quadtree.QuadTree'),
        ),
        migrations.AddField(
            model_name='quadtree',
            name='child_sw',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_south_west', to='quadtree.QuadTree'),
        ),
        migrations.AddField(
            model_name='location',
            name='quadtree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quadtree.QuadTree'),
        ),
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quadtree.User'),
        ),
    ]
